### ISSUE TITLE
Accessor method signature has been changed in v4

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc-label-layout#14]
The accessors are now supplied with `(d, i, nodes)` not sure about context. Many of the accessors are currently broken anyway because they're using fat-arrow + `this`.

**Comment by chrisprice** [comment]
Actually thinking about it, we should add an eslint rule to eliminate any use of `call`, `apply`, `this` and `function` as they are all symptomatic of the old way of doing things.

**Comment by chrisprice** [comment]
And another for `var` with enforced usage of `const` for non-reassigned variables.

**Comment by chrisprice** [comment]
And another for standardising the spacing around the import statements if it exists.

(Think I've got sidetracked)

**Comment by ColinEberhardt** [comment]
We should create our own eslint configuration and add it to npm to make changes like this easier to roll out. Greenkeeper will help no end.

**Comment by ColinEberhardt** [comment]
Unfortunately we cannot eliminate `this`, it is still used as part of `selection.each` https://github.com/d3/d3-selection#selection_each

**Comment by ColinEberhardt** [comment]
Add `arguments` to that list also :-)
