### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by tambua81** [d3fc/d3fc-label-layout#25]
Hello,
I'm drawing a circular genome with d3 and my problem is that, sometimes, labels tend to overlap.
Is there possibility to integrate d3fc-label-layout in my script in order to avoid overlapping?

Thanx in advance,
Claudio

**Comment by ColinEberhardt** [comment]
Sure - it sounds like it should be suitable for that purpose.

**Comment by tambua81** [comment]
Can you help me?
If I could send you my files, we could discuss more in detail.

Thanx in advance,
Claudio

**Comment by ColinEberhardt** [comment]
Hi @tambua81 - I'm afraid I don't have time to provide general assistance. Your best bet is to as a question on StackOverflow:

http://stackoverflow.com

It's a community with many thousands of developers who can help out. I'd read this first though ...

https://stackoverflow.com/help/how-to-ask
