### ISSUE TITLE
Is there a way to give textlabels a class?

### ISSUE THREAD

**Issue by gabrielflorit** [d3fc/d3fc-label-layout#7]
If not, I can try to submit a PR.

By the way this is a great little plugin!

**Comment by ColinEberhardt** [comment]
Hi @gabrielflorit - glad you like it!

The `textLabel` component current creates a `rect`, `circle` and a `text` element. It doesn't actually create a containing element for these. This is similar to the way the D3 scale works.

When used with the label layout, the structure is as follows:

~~~
<g class="label" ...>
    <rect ...></rect>
    <circle ...></circle>
    <text ...>node-11</text>
</g>
~~~

Are you wanting to chance the class of the `g` element that currently has the `label` class?

Within d3fc we have a concept call the [decorate pattern](https://d3fc.io/components/introduction/decorate-pattern.html) which would allow this. Just realised that this component does not conform to this pattern - and probably should! It would allow the following:

~~~
var label = fc_label_layout.textLabel()

var labels = fc_label_layout.label(strategy)
        .size(() => [100, 100])
        .component(label)
        .decorate(sel => sel.enter().classed('my-label', true));
~~~

Which would add the `my-label` class to each label container.

**Comment by gabrielflorit** [comment]
Ah, that would be a nice addition. But I also just realized we could probably do it post-selection, like this: http://bl.ocks.org/mbostock/4403522 .

**Comment by ColinEberhardt** [comment]
Yes, you can use a post-selection. Although, you can see that with an axis that implements the decorate pattern a post-selection isn't required:

https://d3fc.io/components/svg/axis.html

The big advantage here is that you get access to the full selection lifecycle, i.e. enter, exit, update
